name: pages build and deployment

on:
  push:
    branches:
      - main

concurrency:
  group: 'pages-deploy-group'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare site (for static HTML/CSS)
        run: echo "No build step required for static content."

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # هذا يعني نشر كل ما في الجذر

  report-build-status:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Report build status
        run: echo "Deployment process finished successfully."